/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tpcalculadora;

import java.awt.event.KeyListener;
import javax.swing.JTextField;

/**
 *
 * @author Usuario-Gustavo
 */
public class MainCalculadora extends javax.swing.JFrame {

    private static MainCalculadora calculadora;
    
    private MainCalculadora() {
        initComponents();
        misinitComponents();
    }
    //SINGLETON MULTIHILO
    private static class MainCalculadoraHolder{
        public static MainCalculadora calculadora=new MainCalculadora();
    }
    public static synchronized MainCalculadora getInstance()
    {
        
        return MainCalculadoraHolder.calculadora;
    }
    
  /*  //Singleton para un hilo
     //se coloca el constructor como privado para no poder
     //instanciar la clase sino a traves del metodo
     //getInstance

     public static MainCalculadora getInstance(){
          if(calculadora == null){
               calculadora = new MainCalculadora();
          }
          return calculadora;
     }
*/
    
        
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textResultado = new javax.swing.JTextField();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        botondiv = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonigual = new javax.swing.JButton();
        botonc = new javax.swing.JButton();
        botonmulti = new javax.swing.JButton();
        botonmas = new javax.swing.JButton();
        botonmenos = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonminizar = new javax.swing.JLabel();
        botonx = new javax.swing.JLabel();
        barra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(800, 400, 0, 0));
        setMaximizedBounds(new java.awt.Rectangle(800, 300, 200, 200));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textResultado.setEditable(false);
        textResultado.setBackground(new java.awt.Color(0, 0, 0));
        textResultado.setForeground(new java.awt.Color(255, 255, 255));
        textResultado.setMargin(new java.awt.Insets(0, 0, 0, 0));
        getContentPane().add(textResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 30));

        boton7.setText("7");
        boton7.setRequestFocusEnabled(false);
        getContentPane().add(boton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 40, 40));

        boton8.setText("8");
        boton8.setRequestFocusEnabled(false);
        getContentPane().add(boton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 40, 40));

        botondiv.setText("/");
        botondiv.setRequestFocusEnabled(false);
        getContentPane().add(botondiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 40, 40));

        boton0.setText("0");
        boton0.setRequestFocusEnabled(false);
        getContentPane().add(boton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 40, 40));

        botonigual.setText("=");
        botonigual.setRequestFocusEnabled(false);
        getContentPane().add(botonigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 40, 40));

        botonc.setText("C");
        botonc.setRequestFocusEnabled(false);
        getContentPane().add(botonc, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 40, 40));

        botonmulti.setText("*");
        botonmulti.setRequestFocusEnabled(false);
        getContentPane().add(botonmulti, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 40, 40));

        botonmas.setText("+");
        botonmas.setRequestFocusEnabled(false);
        getContentPane().add(botonmas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 40, 40));

        botonmenos.setText("-");
        botonmenos.setRequestFocusEnabled(false);
        getContentPane().add(botonmenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 40, 40));

        boton2.setText("2");
        boton2.setRequestFocusEnabled(false);
        getContentPane().add(boton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 40, 40));

        boton1.setText("1");
        boton1.setRequestFocusEnabled(false);
        getContentPane().add(boton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 40, 40));

        boton5.setText("5");
        boton5.setRequestFocusEnabled(false);
        getContentPane().add(boton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 40, 40));

        boton3.setText("3");
        boton3.setRequestFocusEnabled(false);
        getContentPane().add(boton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 40, 40));

        boton4.setText("4");
        boton4.setRequestFocusEnabled(false);
        getContentPane().add(boton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 40, 40));

        boton6.setText("6");
        boton6.setRequestFocusEnabled(false);
        getContentPane().add(boton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 40, 40));

        boton9.setText("9");
        boton9.setRequestFocusEnabled(false);
        getContentPane().add(boton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tpcalculadora/ifondocalculadora.png"))); // NOI18N
        jLabel1.setRequestFocusEnabled(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 210, 250));

        botonminizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tpcalculadora/botonminimizar01.png"))); // NOI18N
        getContentPane().add(botonminizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 20, 20));

        botonx.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tpcalculadora/botoncerrar01.png"))); // NOI18N
        getContentPane().add(botonx, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 20, 20));

        barra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tpcalculadora/barraventana.png"))); // NOI18N
        barra.setRequestFocusEnabled(false);
        getContentPane().add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              MainCalculadora.getInstance().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barra;
    public javax.swing.JButton boton0;
    public javax.swing.JButton boton1;
    public javax.swing.JButton boton2;
    public javax.swing.JButton boton3;
    public javax.swing.JButton boton4;
    public javax.swing.JButton boton5;
    public javax.swing.JButton boton6;
    public javax.swing.JButton boton7;
    public javax.swing.JButton boton8;
    public javax.swing.JButton boton9;
    public javax.swing.JButton botonc;
    public javax.swing.JButton botondiv;
    public javax.swing.JButton botonigual;
    public javax.swing.JButton botonmas;
    public javax.swing.JButton botonmenos;
    public javax.swing.JLabel botonminizar;
    public javax.swing.JButton botonmulti;
    public javax.swing.JLabel botonx;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField textResultado;
    // End of variables declaration//GEN-END:variables

    private void misinitComponents() {
        
        textResultado.setHorizontalAlignment(JTextField.RIGHT);
        Controlador controlador=new Controlador(this);
        boton0.addActionListener(controlador);
        boton1.addActionListener(controlador);
        boton2.addActionListener(controlador);
        boton3.addActionListener(controlador);
        boton4.addActionListener(controlador);
        boton5.addActionListener(controlador);
        boton6.addActionListener(controlador);
        boton7.addActionListener(controlador);
        boton8.addActionListener(controlador);
        boton9.addActionListener(controlador);
        botonmas.addActionListener(controlador);
        botonmenos.addActionListener(controlador);
        botonigual.addActionListener(controlador);
        botonmulti.addActionListener(controlador);
        botondiv.addActionListener(controlador);
        textResultado.addActionListener(controlador);
        botonc.addActionListener(controlador);
        botonx.addMouseListener(controlador);
        botonminizar.addMouseListener(controlador);
        
        mover mml = new mover(this.barra);
	barra.addMouseListener(mml);
	barra.addMouseMotionListener(mml);
        
        
        textResultado.addKeyListener(controlador);
     
                ;
      
        
    }

    
    
    
    
}
